spring:
    application:
        name: devtoon
    config:
        activate:
            on-profile: dev
    datasource:
        url: jdbc:mysql://${DEV_MYSQL_URL}
        username: ${DEV_MYSQL_USER}
        password: ${DEV_MYSQL_PASSWORD}
    jpa:
        properties:
            hibernate:
                show_sql: true
                format_sql: true
        show-sql: true


