spring:
    application:
        name: devtoon
    config:
        activate:
            on-profile: dev
    data:
        redis:
            host: ${DEV_REDIS_HOST}
            port: ${DEV_REDIS_PORT}
    datasource:
        url: jdbc:mysql://${DEV_MYSQL_URL}
        username: ${DEV_MYSQL_USER}
        password: ${DEV_MYSQL_PASSWORD}
    jpa:
        properties:
            hibernate:
                show_sql: false
                format_sql: false
        show-sql: true
    sql:
        init:
            mode: always # data.sql 파일 실행
    cache:
        type: caffeine


