name: Run Test

on:
    pull_request:
        branches: [develop]
    push:
        branches: [develop]
    workflow_dispatch:

permissions:
    contents: read

jobs:
    Run_Test:
        runs-on: ubuntu-22.04

        services:
            mysql:
                image: mysql:8.0
                env:
                    MYSQL_ROOT_PASSWORD: admin
                    MYSQL_DATABASE: devtoon_db
                    MYSQL_USER: local_user
                    MYSQL_PASSWORD: local_password
                ports:
                    - 3307:3306

        steps:
            - name: 레포지토리 체크아웃
              uses: actions/checkout@v4

            - name: JDK 21 설치
              uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'temurin'

            - name: gradlew 권한을 부여합니다.
              run: chmod +x ./gradlew

            - name: Gradle을 통해 빌드합니다.
              run: ./gradlew build

            - name: 테스트용 application.yaml을 작성합니다.
              run: |
                  mkdir -p src/test/resources
                  echo "${{ secrets.APPLICATION_TEST_YML }}" | base64 --decode > src/test/resources/application.yaml

            - name: run test
              run: ./gradlew clean test