name: Run Test

on:
    push:
        branches:
            - develop

jobs:
    Run_Test:
        runs-on: ubuntu-latest

        services:
            mysql:
                image: mysql:8.0
                env:
                    MYSQL_ROOT_PASSWORD: admin
                    MYSQL_DATABASE: devtoon_db
                    MYSQL_USER: local_user
                    MYSQL_PASSWORD: local_password
                ports:
                    - 3307:3306

        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: java setup
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: '21'

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v3

            - name: setup application.yaml
              run: |
                  mkdir -p src/test/resources
                  echo "${{ secrets.APPLICATION_TEST_YML }}" | base64 --decode > src/test/resources/application.yml

            - name: make executable gradlew
              run: chmod +x ./gradlew

            - name: run test
              run: ./gradlew clean test